### ISSUE TITLE
HTTP Basics Auth. Solution

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canbican/wordpress-java#47]
```
Hello, 
sorry for my english 

My Problem was: my wordpress-backend is under HTTP basic Auth.
I found a solution
If you think this solution is usefull for the project, than you are free to add 
this source with youre copyright.

Wordpress.java ist based on last september release.

Thanks for the projekt


 by
Nikolai Ziegler


```

Original issue reported on code.google.com by `Nikolai....@gmail.com` on 6 Oct 2013 at 5:30

Attachments:
- [Wordpress.java](https://storage.googleapis.com/google-code-attachments/wordpress-java/issue-47/comment-0/Wordpress.java)

**Comment by canbican** [comment]
We need a pull request for the latest version, I'll be happy to include it.
