### ISSUE TITLE
How to setCategories for Post

### ISSUE THREAD

**Issue by 123one** [canbican/wordpress-java#50]
Hello,
Could you show me how can I setCategories for Post?
I try to
List<Category> categories = wp.getCategories();
Page recentPost = new Page();
Category cat = cat = categories.get(0);
XmlRpcArray cats = new XmlRpcArray();
recentPost.setCategories(cats);
String result = wp.newPost(recentPost, true);

but it always in Uncategorized

Thank you!

**Comment by canbican** [comment]
First of all, I suggest you use the latest version.

Also, you need to create a new Term of type category (either using the API or wordpress GUI) in order to select it.
