### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by bodiam** [canbican/wordpress-java#54]
When using Gradle, only adding the dependency doesn't work. You'll also need to add the jboss repository, else the redstone library cannot be found:

```
    maven {
        url "https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/"
    }
```

Maybe it would be nice to update the installation manual for that?

**Comment by canbican** [comment]
It's an auto-generated page, by the maven site command. I've never tried building with anything other than maven. I'll have a look if it's possible without having to write that whole page manually.

**Comment by sembozdemir** [comment]
Thank you @bodiam

**Comment by erichirlemann** [comment]
For maven, I had to add:

``` xml
<repositories>
    <repository>
      <id>redstone.xmlrpc</id>
      <url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>
    </repository>
 </repositories>
```

Thank you @bodiam

**Comment by canbican** [comment]
@erichirlemann It was already in the pom.xml, didn't it make it to your maven dependencies?

**Comment by AchrafAmil** [comment]
I had the same issue (Android Studio gradle). After 30 minutes of research I finally found the right repositories and the dependencies to add. If only I saw bodiam issue, that would have saved me lot of time.
Thank you anyway, big up :')

**Comment by canbican** [comment]
There is a larger problem here though. I think the tendency to use Gradle is more about developing for Android. However, the underlying xmlrpc library which you try to include has a license incompatible with Google Play store. It looks like the author doesn't care much, but the license is there and I don't think you can bundle it in your Android application and put it on store - unless you distribute it adhoc and provide means to access the source code of it from the same place.

If you are developing for a company, consult your lawyer and don't make its author rich. Oh but never mind, he wrote a good library he deserves it :)
