### ISSUE TITLE
redstone.xmlrpc.XmlRpcException

### ISSUE THREAD

**Issue by vpoli** [canbican/wordpress-java#55]
Hi All, 
I'm trying to run the following code, which was working same days ago: 

Wordpress wp = new Wordpress(username, password, blogApiUrl);
final FilterPost filter = new FilterPost();
        filter.setNumber(10);
        List<Post> recentPosts;
        try
        {
            recentPosts = wp.getPosts(filter);
            System.out.println("Here are the ten recent posts:");
            for (final Post page : recentPosts)
            {
                System.out.println(page.getPost_id() + ":" + page.getPost_title());
            }
        }
        catch (final XmlRpcFault | XmlRpcException e)
        {
            throw new CMSException(e);
        }

where the blogApiUrl is correcly set to http://localhost:90/wordpress/xmlrpc.php (I get the page in the browser). 
But now I get this error: 
[Fatal Error] :3:6: Non è consentita una destinazione di istruzione di elaborazione corrispondente a "[xX][mM][lL]".
Exception in thread "main" trasparcency.exception.CMSException: redstone.xmlrpc.XmlRpcException: The response could not be parsed.
    at trasparcency.publishing.WordpressPublisher.readPosts(WordpressPublisher.java:255)
    at trasparcency.publishing.WordpressPublisher.test(WordpressPublisher.java:153)
    at trasparcency.publishing.WordpressPublisher.main(WordpressPublisher.java:43)
Caused by: redstone.xmlrpc.XmlRpcException: The response could not be parsed.
    at redstone.xmlrpc.XmlRpcClient.handleResponse(Unknown Source)
    at redstone.xmlrpc.XmlRpcClient.endCall(Unknown Source)
    at redstone.xmlrpc.XmlRpcClient.invoke(Unknown Source)
    at redstone.xmlrpc.XmlRpcProxy.invoke(Unknown Source)
    at net.bican.wordpress.$Proxy0.getPosts(Unknown Source)
    at net.bican.wordpress.Wordpress.getPosts(Wordpress.java:822)
    at trasparcency.publishing.WordpressPublisher.readPosts(WordpressPublisher.java:246)
    ... 2 more
Caused by: redstone.xmlrpc.XmlRpcException: A problem occured during parsing
    at redstone.xmlrpc.XmlRpcParser.parse(Unknown Source)
    ... 9 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 6; Non è consentita una destinazione di istruzione di elaborazione corrispondente a "[xX][mM][lL]".
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
    ... 10 more

The problem is that any type of call provides the same error (getPost, newPost and so on...). 
Could you give me any suggestion, please?

**Comment by canbican** [comment]
Can you please translate the saxparseexception for me? Google translate failed to elaborate :)

**Comment by mcastets** [comment]
I suddenly (always worked until today) get the same error when calling newPost(Post post) :

> Caused by: redstone.xmlrpc.XmlRpcException: The response could not be parsed.
>     at redstone.xmlrpc.XmlRpcClient.handleResponse(Unknown Source)
>     at redstone.xmlrpc.XmlRpcClient.endCall(Unknown Source)
>     at redstone.xmlrpc.XmlRpcClient.invoke(Unknown Source)
>     at redstone.xmlrpc.XmlRpcProxy.invoke(Unknown Source)
>     at net.bican.wordpress.$Proxy599.newPost(Unknown Source)
>     at net.bican.wordpress.Wordpress.newPost(Wordpress.java:1316)
>     at com.ubicv.metier.social.WordPress.newCompanyPost(WordPress.java:271)
>     at sun.reflect.GeneratedMethodAccessor4495.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
>     at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
>     at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
>     at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
>     at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
>     at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
>     at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
>     at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
>     at sun.reflect.GeneratedMethodAccessor463.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
>     at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
>     at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
>     at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
>     at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
>     at sun.reflect.GeneratedMethodAccessor464.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
>     at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
>     at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
>     at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
>     at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
>     at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
>     ... 4 more
> Caused by: redstone.xmlrpc.XmlRpcException: A problem occured during parsing
>     at redstone.xmlrpc.XmlRpcParser.parse(Unknown Source)
>     ... 39 more
> Caused by: org.xml.sax.SAXParseException; lineNumber: 56; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.
>     at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
>     ... 40 more
> ]]
> 
> [2016-01-29T15:39:45.941+0000] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=345 _ThreadName=Thread-9] [timeMillis: 1454081985941] [levelValue: 1000] [[
>   [Fatal Error] :56:6: The processing instruction target matching "[xX][mM][lL]" is not allowed.]]

**Comment by mcastets** [comment]
> Caused by: org.xml.sax.SAXParseException; lineNumber: 56; columnNumber: 6

Is it possible to get access to (or log) the XML response?

**Comment by vpoli** [comment]
Hi all, 
I guess your problem is the same as mine! I was working on wordpress theme internal files and I accidentally modified the file function.php (probably adding a white line which made the xml response unparsable). I solved with a fresh installation of my theme. I found the hint here: http://www.wpbeginner.com/beginners-guide/14-most-common-wordpress-errors-and-how-to-fix-them/

**Comment by canbican** [comment]
It is possible to log the XML response on Wordpress part. It used to be setting 'xmlrpc_logging' in the configuration but now it's deprecated. The comment offers error_log() instead.

On the library side, no :)

**Comment by mcastets** [comment]
Thanks for the hints. 

> log the XML response on Wordpress part

Could you please tell me the path to the file where I can use error_log()?

**Comment by mcastets** [comment]
OK, I found the culprit, it was a plug-in (Social Networks Auto Poster {SNAP}). It works again when I disable it. 

Thank you.

**Comment by canbican** [comment]
I couldn't figure out how error_log is supposed to work. I have a shamelessly modified class-wp-xmlrpc-server.php that logs only what I care for. It's not good for any use, and belongs to an older version of wordpress, so I doubt I should share it :)
