### ISSUE TITLE
Pass XmlRpcFault message up

### ISSUE THREAD

**Issue by marlier** [canbican/wordpress-java#56]
I attempted to use the following to edit an existing post:

```
Post post = client.getPost(postId);
post.setPost_content(updatedContent);
boolean updateSucceeded = client.editPost(postId, post);
```

This returned an InsufficientRightsException().

Digging in, it turns out that the actual underlying exception was an XmlRpcFault, with the following message:

```
redstone.xmlrpc.XmlRpcFault: Sorry, one of the given taxonomies is not supported by the post type.
```

Needless to say, it would have been helpful to have the message passed up.

**Comment by canbican** [comment]
https://github.com/canbican/wordpress-java/commit/cce448cee75cf890cf381fd4e1017bb0eb52288b
