### ISSUE TITLE
Getting XmlRpcException when I try to add a custom taxonomy to the post

### ISSUE THREAD

**Issue by ghost** [canbican/wordpress-java#57]
Hello, 
   When I try to add a custom taxonomy, I get the following error: 

> Exception in thread "main" redstone.xmlrpc.XmlRpcException: The response could not be parsed.

It works fine when I add a category or a tag. 
The line where it gives error is:  
`final List<Term> terms = wp.getTerms("author");`  

My custom taxonomy is author. If I swap "author" with "category" or "post_tag", the code goes through and it adds the category or tag with the post. But when I try to use the same code for a custom taxonomy,  I get the error. 

Is there another way to use custom taxonomy? 
thanks,

**Comment by canbican** [comment]
Do you have the custom taxonomy already defined in the installation?
