### ISSUE TITLE
Update exemples and thumbs

### ISSUE THREAD

**Issue by ghost** [canbican/wordpress-java#67]
Hi,

I've found some examples of how set a thumbnail on a post but don't work with new version. Someone know how does it work and can update exemples ?

Thank you !

**Comment by aliakseiz** [comment]
Works for me on latest version.

```
MediaItemUploadResult uploadResult = uploadImage(img, wpPost.getPost_id()); 
MediaItem mediaItem = wp.getMediaItem(uploadResult.getId());
wpPost.setPost_thumbnail(mediaItem);
```

My Wordpress theme requires custom field `_thumbnail_id` to be set for each post, so I put `wpPost.getPost_thumbnail().getAttachment_id()` to `"_thumbnail_id"` additionally.

Can you provide a code, that you have tried? Are any exceptions thrown? 
Your theme might also require some additional values to be stored for thumbnail, what theme do you use?

**Comment by ghost** [comment]
Thanks for your answer, I've try this:

`MediaItemUploadResult uploadResult = wp.uploadFile(new FileInputStream(f), this.name + "_thumb.png"); 
            MediaItem mediaItem = wp.getMediaItem(uploadResult.getId());
            newPost.setPost_thumbnail(mediaItem);`

But that just upload file without add it to the post's thumb. Nothing in postmeta database table :/
My theme is tribal.

**Comment by aliakseiz** [comment]
**1. Java client:**

```
            Wordpress wp = new Wordpress("admin", "admin", "http://localhost/xmlrpc.php");

            // initialize post
            Post wpPost = new Post();
            wpPost.setPost_title("Title");
            wpPost.setPost_content("Content");

            // upload image
            InputStream f = new FileInputStream("C:\\img.jpg");
            MediaItemUploadResult uploadResult = wp.uploadFile(f, "img.jpg", true);
            MediaItem mediaItem = wp.getMediaItem(uploadResult.getId());

            // assign it as a thumbnail
            CustomField customField = new CustomField();
            customField.setKey("_thumbnail_id");
            customField.setValue(String.valueOf(mediaItem.getAttachment_id()));
            wpPost.setCustom_fields(Arrays.asList(customField));

            // create post
            wp.newPost(wpPost);
```

**2. Wordpress**
To allow creation of protected fields in Wordpress, add this line somehwere (during testing I put it in _class-wp-xmlrpc-server.php_ as first line in _ _insert_post_ method):
`register_meta( 'post', '_thumbnail_id', 'absint', '__return_true' );`

See this post for more info: [Playing with XML-RPC and underscored custom fields](http://wordpress.stackexchange.com/questions/166081/xmlrpc-and-underscored-custom-fields)

Tested on Wordpress 4,6,1, Tribal 1.0

**Comment by ghost** [comment]
Work in database and in wp-admin ! But doesn't show thumbnail on my theme I'll try on an other theme. Thank you !
