### ISSUE TITLE
JWordpress Permissions Issue

### ISSUE THREAD

**Issue by fuchstim** [canbican/wordpress-java#68]
Hello everyone!
I am currently building an app that fetches posts from my wordpress blog and displays them in a listview, all with short text, pictures and stuff. So far the JWordpress library is working just fine, except for one small issue:
I am using a specific 'app' user on my blog to read the posts. Therefore the user should only be able to **read** the posts, and not publish or edit anything, the password is hardcoded into the app after all.
But still, it requires the following four wordpress-permissions to even load the posts at all:

1. edit_others_posts
2. edit_posts
3. edit_private_posts
4. edit_published_posts

It does not care about any read_* permissions.

If one ore more of these permissions are not granted, it will print out:
`redstone.xmlrpc.XmlRpcFault: Sorry, you are not allowed to edit posts in this post type. [and so on]`

Is there any way to tell it that it doesnt need any write permissions? I really do not feel good about rolling out an update with wordpress-credentials capable of posting stuff...

-rocketdoge

_**EDIT**_

I have just set up a completely blank WP-Blog just to eliminate that the error is caused by my blog-setup.
The error persists.

**Comment by canbican** [comment]
It's really about the wordpress itself when it comes to permissions. Have a look at the code:

https://github.com/WordPress/WordPress/blob/6b1532f96b101e0bc6fb7d34eebdf966b0620cbc/wp-includes/class-wp-xmlrpc-server.php#L1798

getPosts() require edit_posts, beats me why. Maybe you can ask about it to wordpress guys.
