### ISSUE TITLE
Get all taxonomies related to a post

### ISSUE THREAD

**Issue by vsmadhu** [canbican/wordpress-java#72]
Hi, Label:question

I am trying to get all the taxonomies  related to a post and couldn't find a example in the wiki page Example Code section for the same.

Could you please add a sample code as how I can do that.
I have enclosed all the steps I have already tired.
in the file named TaxonomieLoader.java

Thanks in advance :-)

**Comment by vsmadhu** [comment]
Please rename the file to .java

What I trying to do is get the taxonomies applied to a given post.
I am able to print all the taxonomies but there is no way to get the taxonomies applied to a given post.

[TaxonomieLoader.txt](https://github.com/canbican/wordpress-java/files/817561/TaxonomieLoader.txt)

**Comment by canbican** [comment]
I'm going to write a wiki page about taxonomies in the weekend - hopefully. Let me know if it helps then.

**Comment by vsmadhu** [comment]
Hi

Thank you appreciate you writing a wiki on this, I am sure it most certainly will be helpful to a lot of api user 

Cheers
Madhu
