### ISSUE TITLE
Get the menu structure related to a post (nav_menu_item)

### ISSUE THREAD

**Issue by ghost** [canbican/wordpress-java#73]
Hi,

like the taxonomies, I'd like to get the menu structure (post_type: nav_menu_item) related to a post.

The following example lists the menu structure, bit I can not find, how I can get the related posts.

final FilterPost filter = new FilterPost();
filter.setPost_type("nav_menu_item");
final List<Post> posts = wp.getPosts(filter);
for (final Post wordpressPost : posts) {
    System.out.println("wordpressPost " + ToStringBuilder.reflectionToString(wordpressPost));
}

Thanks in advance!

Btw, thank you very much for your initiative and engagement (wordpress-java)! It's very helpful!

Best regards, Klaus

**Comment by canbican** [comment]
I'm going to write a wiki page about taxonomies in the weekend - hopefully. Let me know if it helps then.
