### ISSUE TITLE
importing jar file gives error while running android app

### ISSUE THREAD

**Issue by muthu1001** [canbican/wordpress-java#75]
Wordpress wp1=new Wordpress("user_name","pass_word","xmlrpcurl");

java.lang.NoClassDefFoundError:
 Failed resolution of: Lredstone/xmlrpc/XmlRpcProxy;
at net.bican.wordpress.Wordpress.initMetaWebLog(Wordpress.java:124)
at net.bican.wordpress.Wordpress.<init>(Wordpress.java:74)

**Comment by canbican** [comment]
Check maven dependencies, you are missing Redstone xml-rpc library.

**Comment by muthu1001** [comment]
Redstone xml-rpc library 
tell me the dependency to be added
