### ISSUE TITLE
Issue in setCategoryIds function

### ISSUE THREAD

**Issue by pborgesalves** [canbican/wordpress-java#78]
Hello,
I'm trying to attribute a category id to a post but the post is always assigned to Uncategorized category.
post.setCategoryIds(list);
client.createPost(post, PostStatus.publish);

Do you know if I'm doing something wrong?
Thank you

**Comment by canbican** [comment]
Use terms, they're the new categories :) An example is here:

https://github.com/canbican/wordpress-java/wiki/Taxonomies-and-Terms-of-a-Post
