### ISSUE TITLE
Feature: Changing User Agent

### ISSUE THREAD

**Issue by hypery2k** [canbican/wordpress-java#81]
Would be great to allow a custom user agent for the client library. Is this possible?

**Comment by canbican** [comment]
https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

It seems that it can be set via system properties. I haven't tried though.

**Comment by hypery2k** [comment]
yes thats working, but the java-version is still appended, [see](https://stackoverflow.com/questions/15845075/set-user-agent-property-in-https-connection-header#16027704).

**Comment by canbican** [comment]
It would require changes to the underlying xml-rpc library. I'm not ready to take it over yet :)
