### ISSUE TITLE
Can not add image to post

### ISSUE THREAD

**Issue by fsolans** [canbican/wordpress-java#82]
Hi,

I'm using 0.7.0 release and when I'm creating a new post with a thumbnail  but it is not attached to post.

`
// Upload image
InputStream is = new FileInputStream(new File("/home/fsolans/Escritorio/" + "neodoo_logo.png"));
//InputStream is = new URL(imageUrl).openStream();

// https://github.com/canbican/wordpress-java/issues/67#issuecomment-258135285
String filename = "neodoo_logo.png"; //IMG_SELLER_LOGO + idUserSeller;
MediaItemUploadResult imageUploaded = wp.uploadFile(is, filename, true);
MediaItem mediaItem = wp.getMediaItem(imageUploaded.getId());			
post.setPost_thumbnail(mediaItem);
`
Thks!

**Comment by canbican** [comment]
Wordpress-java does not work as clever as Hibernate :) After setting the post thumbnail, you need to commit it back. So your missing command is wp.newPost or wp.editPost.
