### ISSUE TITLE
JWordpress not completing transaction in GUI app

### ISSUE THREAD

**Issue by vvvilela** [canbican/wordpress-java#85]
I'm trying to update a Wordpress blog in a Windows GUI application, but the transactions (eg, get authors, new post) don't complete. Task Manager shows that the thread is active, consuming CPU (~30%) and increasing memory usage, but... forever. In batch mode read and upload are normal.

I made some tests with threads, but in a kind of trial-and-error approach, I don't really have clues. The results so far (access "before" and "after" refer to running JWordpress before or after creating a JFrame):

 * - Batch, main thread (MT): ok
 * - Batch, other thread: ok
 * - MT with frame, acess before: ok
 * - MT with frame, acess after: NOK
 * - Frame in EDT, acess before: ok
 * - Frame in EDT, acess after: NOK
 * - Frame in EDT, WP em thread, acess before: NOK
 * - Frame in EDT, WP em thread, acess after: NOK
 * - Both in EDT: before and after NOK

**Comment by canbican** [comment]
I suppose we need source code level debugging, do you have access to it?

**Comment by vvvilela** [comment]
The execution stopped at line 258 of Wordpress class:
      final Boolean r = this.wp.editPost(BLOGID, this.username, this.password, postId, postX);
After this there is an interface (WordpressBridge) and I didn't have access to the implementation.

Thank you anyway, I will not be using the API anymore. I decided to avoid certain APIs, for example for XML-RPC and REST. To program by myself take a while, but it is one learning curve like other options, code is simpler and, mainly, there are, it seems, less critical risks like this one.

**Comment by canbican** [comment]
Exactly. XML-RPC used by this library prohibits closed source distribution. Stay away when you can't access the source code of it.
